export const defaults = {
    margin: {
        top: 35,
        right: 15,
        bottom: 25,
        left: 15
    },
    logo: { width: 32, height: 9.938, x: 15, y: 12 },
    title: '',
    subtitle: '',
    filename: 'document.pdf',
    format: 'a4',
    orientation: 'portrait',
    unit: 'mm',
    showHeader: true,
    showFooter: true,
    showPageNumber: true,
    showLogo: true,
    showDate: true,
    styles: {
        headerTitle: { font: 'helvetica', fontSize: 15, textColor: '#02A5A5', fontWeight: 'bold' },
        title: { font: 'helvetica', fontSize: 12, textColor: '#004481', fontWeight: 'bold'},
        subtitle: { font: 'helvetica', fontSize: 12, textColor: '#1464A5'},
        footer: { font: 'helvetica', fontSize: 8, textColor: '#121212'},
        date: { font: 'helvetica', fontSize: 8, textColor: '#666666', fontWeight: 'normal' },
        dateFormat: { locale: 'en-US', options: { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' } },
        pageNumber: { font: 'helvetica', fontSize: 8, textColor: '#666666', fontWeight: 'normal' },
        text: { font: 'helvetica', fontSize: 8, textColor: '#121212', fontWeight: 'normal' },
        circle: {fillColor: '#D3D3D3', drawColor: '#121212', lineWidth: 0.2},
        rect: {fillColor: '#D3D3D3', drawColor: '#121212', lineWidth: 0.2},
        line: {fillColor: '#D3D3D3', drawColor: '#121212', lineWidth: 0.2},
        chart: {},
        table: {
            font: 'helvetica',
            fontStyle: 'normal',
            overflow: 'linebreak',
            fillColor: 255,
            textColor: 20,
            cellWidth: 'auto',
            minCellWidth: 10,
            minCellHeight: 0,
            halign: 'left',
            valign: 'top',
            fontSize: 9,
            cellPadding: {top: 1.5, right: 1.5, bottom: 1.5, left: 1.5},
            lineColor: 200,
            lineWidth: {top: 0.1, right: 0.1, bottom: 0.2, left: 0.1},
            theme: 'plain',
            pageBreak: 'auto',
            rowPageBreak: 'auto',
            tableWidth: 'auto',
            showHead: 'firstPage',
            showFoot: 'lastPage',
            tableLineWidth: 0,
            tableLineColor: 200
        },
        values: {
            font: 'helvetica',
            fontStyle: 'normal',
            overflow: 'linebreak',
            fillColor: 255,
            textColor: 20,
            minCellWidth: 10,
            minCellHeight: 0,
            maxCellHeight: 4,
            halign: 'left',
            valign: 'top',
            fontSize: 9,
            cellPadding: {top: 1, right: 1.5, bottom: 1, left: 0},
            lineColor: 200,
            lineWidth: {top: 0, right: 0, bottom: 0.2, left: 0},
            theme: 'plain',
            pageBreak: 'auto',
            rowPageBreak: 'auto',
            showHead: 'never',
            showFoot: 'never',
            tableLineWidth: 0,
            tableLineColor: 200
        },
        values2: {
            font: 'helvetica',
            fontStyle: 'normal',
            overflow: 'linebreak',
            fillColor: 255,
            textColor: 20,
            minCellWidth: 10,
            minCellHeight: 0,
            maxCellHeight: 4,
            halign: 'left',
            valign: 'top',
            fontSize: 9,
            cellPadding: {top: 1, right: 1.5, bottom: 1, left: 0},
            lineColor: 200,
            lineWidth: {top: 0, right: 0, bottom: 0.2, left: 0},
            theme: 'plain',
            pageBreak: 'auto',
            rowPageBreak: 'auto',
            showHead: 'never',
            showFoot: 'never',
            tableLineWidth: 0,
            tableLineColor: 200
        },
        headStyles: { fontStyle: 'bold', textColor: [33, 33, 33], fillColor: [242, 242, 242], fontSize: 9 },
        bodyStyles: {}
    },

}