export const dealDescriptionFields = [
    {
        id: 'DMT_Deal_amount__c',
        label: 'Deal amount',
        apiName: 'DMT_Deal_amount__c',
        value: 0,
        size: '1-of-2',
        type: 'numberWithSuffix',
        extraText: 'Units EUR',
        isReadOnly: false,
        isHidden: false,
        isRequired: true,
        step: 0.01,
        min: 0,
        max: 99999999999999.99
    },
    {
        id: 'bbva_prtcp_tranche_amount__c',
        label: 'BBVA commitment amount',
        apiName: 'bbva_prtcp_tranche_amount__c',
        value: 0,
        size: '1-of-2',
        type: 'numberWithSuffix',
        extraText: 'EUR',
        isReadOnly: true,
        isHidden: false,
        isRequired: true,
        step: 0.01,
        min: 0,
        max: 99999999999999.99
    },
    {
        id: 'DMT_NewMoney_BBVA__c',
        label: 'New money for BBVA',
        apiName: 'DMT_NewMoney_BBVA__c',
        value: null,
        size: '1-of-2',
        type: 'numberWithSuffix',
        extraText: 'EUR',
        isReadOnly: false,
        isHidden: false,
        isRequired: true,
        step: 0.01,
        min: 0,
        max: 99999999999999.99
    },
    {
        id: 'DMT_OldMoney_BBVA__c',
        label: 'Old money for BBVA',
        apiName: 'DMT_OldMoney_BBVA__c',
        value: 0,
        size: '1-of-2',
        type: 'numberWithSuffix',
        extraText: 'EUR',
        isReadOnly: true,
        isHidden: false,
        isRequired: true,
        step: 0.01,
        min: 0,
        max: 99999999999999.99
    },
    {
        id: 'syndicated_loan_drawn_amount__c',
        label: 'Expected BBVA Final Take',
        apiName: 'syndicated_loan_drawn_amount__c',
        value: null,
        size: '1-of-2',
        type: 'numberWithSuffix',
        extraText: 'EUR',
        isReadOnly: false,
        isHidden: false,
        isRequired: true,
        //helpText: 'Ejemplo',
        step: 0.01,
        min: 0,
        max: 99999999999999.99
    },
    {
        id: 'DMT_Expected_Drawn__c',
        label: 'Expected Drawn (%)',
        apiName: 'DMT_Expected_Drawn__c',
        value: 0,
        size: '1-of-2',
        type: 'number',
        isReadOnly: false,
        isHidden: false,
        isRequired: true,
        step: 0.01,
        min: 0,
        max: 100
    },
    {
        id: 'entity_role_type__c',
        label: 'Role of BBVA',
        apiName: 'entity_role_type__c',
        value: '',
        size: '1-of-2',
        type: 'multipicklist',
        isReadOnly: false,
        isHidden: false,
        isRequired: false,
        options: [
            { label: 'Agent', value: 'Agent' },
            { label: 'Coordinator', value: 'Coordinator' },
            { label: 'Bookrunner', value: 'Bookrunner' },
            { label: 'MLA', value: 'MLA' },
            { label: 'Participant', value: 'Participant' },
            { label: 'Bilateral', value: 'Bilateral' },
            { label: 'ESG Coordinator', value: 'ESG Coordinator' }
        ]
    },
    {
        id: 'DMT_Sub_Limit__c',
        label: 'Sub-limit (if any)',
        apiName: 'DMT_Sub_Limit__c',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: false,
        isHidden: false,
        isRequired: false
    }
];