/**-------------------------------------------------------------------------------------------
* @Name     HPG CapitalProvision
* @Author
* @Date     Created: 2023-07-18
* ------------------------------------------------------------------------------------------------
* @Description Wrapper Class for request operations service
* ------------------------------------------------------------------------------------------------
*/
public with sharing class DMT_HPG_CapitalProvision {
    public static void testing() {
        system.debug('test mock');
    }
}