// TODO: Add actual field API names from Salesforce once confirmed
export const dealMainFields = [
  {
    id: "DMT_Commitment_Deadline__c",
    label: "Commitment Deadline",
    apiName: "DMT_Commitment_Deadline__c",
    objectType: 'DMT_Opportunity_Client__c',
    value: "",
    size: "1-of-2",
    type: "date",
    isReadOnly: false,
    isHidden: false,
    isRequired: false
  },
  {
    id: "DMT_Description_Issues__c",
    label: "Description of the deal",
    apiName: "DMT_Description_Issues__c",
    objectType: 'DMT_Opportunity_Client__c',
    value: "",
    size: "1-of-2",
    type: "textarea",
    isReadOnly: false,
    isHidden: false,
    isRequired: false,
    maxLength: "3085",
    showCharacterCounter: true
  },
  {
    id: "DMT_Purpose__c",
    label: "Purpose",
    apiName: "DMT_Purpose__c",
    objectType: 'DMT_Opportunity_Client__c',
    value: "",
    size: "1-of-2",
    type: "textarea",
    isReadOnly: false,
    isHidden: false,
    isRequired: false,
    maxLength: "206",
    showCharacterCounter: true,
    nbcScope: 'Global', // Only for Global NBC — shown when Product Area is GTB
  },
  {
    id: "DMT_Opp_Threats_Related_Deal__c",
    label: "Opportunities & Threats Related to the Deal",
    apiName: "DMT_Opp_Threats_Related_Deal__c",
    objectType: 'DMT_Opportunity_Client__c',
    value: "",
    size: "1-of-2",
    type: "textarea",
    isReadOnly: false,
    isHidden: false,
    isRequired: false,
    maxLength: "812",
    showCharacterCounter: true,
    nbcScope: 'Global',
  },
  {
    id: "DMT_History_Deal__c",
    label: "History of the Deal",
    apiName: "DMT_History_Deal__c",
    objectType: 'DMT_Opportunity_Client__c',
    value: "",
    size: "1-of-1",
    type: "textarea",
    isReadOnly: false,
    isHidden: false,
    isRequired: false,
    maxLength: "2034",
    showCharacterCounter: true,
    nbcScope: 'Global',
  }
  /* {
    id: "DMT_Exception_Pool__c",
    label: "Exception Pool",
    apiName: "DMT_Exception_Pool__c",
    value: "",
    size: "1-of-2",
    type: "picklist",
    isReadOnly: false,
    isHidden: false,
    isRequired: false,
    options: []
  },
  {
    id: "DMT_Tiering_Action__c",
    label: "Tiering Action",
    apiName: "DMT_Tiering_Action__c",
    value: "",
    size: "1-of-2",
    type: "picklist",
    isReadOnly: false,
    isHidden: false,
    isRequired: false,
    options: []
  },
  {
    id: "DMT_Target__c",
    label: "Target",
    apiName: "DMT_Target__c",
    value: "",
    size: "1-of-2",
    type: "text",
    isReadOnly: false,
    isHidden: false,
    isRequired: false
  } */
];