export const oppInfoFields = [
    {
        id: 'Name',
        label: 'Name',
        apiName: 'Name',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: false,
        isHidden: false,
        isRequired: false,
        options: []
    },
    {
        id: 'Entific__c',
        label: 'Entific',
        apiName: 'Entific__c',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: true,
        isHidden: false,
        isRequired: false
    },{
        id: 'DMT_Entity__c',
        label: 'Entity',
        apiName: 'DMT_Entity__c',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: true,
        isHidden: false,
        isRequired: false,
    },
    {
        id: 'DMT_branch_id_c__c',
        label: 'Booking Country',
        apiName: 'DMT_branch_id_c__c',
        value: '',
        size: '1-of-2',
        type: 'picklist',
        isReadOnly: false,
        isHidden: false,
        isRequired: false,
        options: []
    },
    {
        id: 'DMT_Booking_EFAN__c',
        label: 'Booking EFAN',
        apiName: 'DMT_Booking_EFAN__c',
        value: '',
        size: '1-of-2',
        type: 'picklist',
        isReadOnly: false,
        isHidden: false,
        isRequired: false,
        options: []
    },
    {
        id: 'CloseDate',
        label: 'Estimated Closing Date',
        apiName: 'CloseDate',
        value: '',
        size: '1-of-2',
        type: 'date',
        isReadOnly: false,
        isHidden: false,
        isRequired: false
    },
    {
        // Formula field: TEXT((YEAR(MaturityDate)-YEAR(InitDate))*12 + MONTH(MaturityDate)-MONTH(InitDate)) + " month(s)"
        // Read-only — computed by Salesforce
        id: 'DMT_Tenor__c',
        label: 'Opportunity Tenor',
        apiName: 'DMT_Tenor__c',
        value: 12,
        size: '1-of-2',
        min: 0,
        type: 'numberWithSuffix',
        isReadOnly: true,
        isHidden: false,
        isRequired: false,
        extraText: 'Month(s)',
        showCounterButtons: false 
    },
    {
        id: 'DMT_CUR_Notional_Amount__c',
        label: 'Opportunity BBVA commitment amount ',
        apiName: 'DMT_CUR_Notional_Amount__c',
        value: 0,
        size: '1-of-2',
        type: 'textWithSuffix',
        extraText: 'EUR',
        isReadOnly: true,
        isHidden: false,
        isRequired: false,
    },{
        id: 'DMT_Opportunity_amount__c',
        label: 'Opportunity Deal Amount',
        apiName: 'DMT_Opportunity_amount__c',
        value: 0,
        size: '1-of-2',
        type: 'textWithSuffix',
        extraText: 'EUR',
        isReadOnly: true,
        isHidden: false,
        isRequired: false,
        nbcScope: 'Global', // Only for Global NBC — shown when Product Area is GTB
    },
    {
        id: 'DMT_CurrencyText__c',
        label: 'Currency',
        apiName: 'DMT_CurrencyText__c',
        value: '',
        size: '1-of-2',
        type: 'picklist',
        isReadOnly: false,
        isHidden: false,
        isRequired: true,
        options: []
    },
    {
        id: 'DMT_Capital_Action__c',
        label: 'Capital Action',
        apiName: 'DMT_Capital_Action__c',
        value: '',
        size: '1-of-2',
        type: 'picklist',
        isReadOnly: false,
        isHidden: false,
        isRequired: false,
        options: [
            { label: 'Amendment', value: 'Amendment' },
            { label: 'A&E (Amend & Extend)', value: 'A&E (Amend & Extend)' },
            { label: 'Extension RCF & TL', value: 'Extension RCF & TL' },
            { label: 'New Facility', value: 'New Facility' },
            { label: 'Refinancing', value: 'Refinancing' }, 
        ]
    },
    {
        id: 'DMT_Product_Area__c',
        label: 'Product Area',
        apiName: 'DMT_Product_Area__c',
        value: '',
        size: '1-of-2',
        type: 'picklist',
        isReadOnly: false,
        isHidden: false,
        isRequired: true,
        options: [
            { label: 'IB&F', value: 'IB&F' }, 
            { label: 'GTB', value: 'GTB   ' }
        ]
    },
    {
        id: 'DMT_ContingentCommitments__c',
        label: 'Contingent Commitments',
        apiName: 'DMT_ContingentCommitments__c',
        value: '',
        size: '1-of-2',
        type: 'picklist',
        isReadOnly: false,
        helpText: 'Confirm if this deal is about an acquisition financing subject to customary regulatory approvals.',
        isHidden: true,
        isRequired: false,
        options: [
            { label: 'Yes', value: 'Yes' }, 
            { label: 'No', value: 'No' }
        ]
    },
    {
        id: 'DMT_Structured_GTB__c',
        label: 'Structured GTB',
        apiName: 'DMT_Structured_GTB__c',
        value: false,
        size: '1-of-2',
        type: 'checkbox',
        isReadOnly: false,
        isHidden: true,
        isRequired: false
    },
    {
        id: 'DMT_Confidential__c',
        label: 'Confidential',
        apiName: 'DMT_Confidential__c',
        value: false,
        size: '1-of-2',
        type: 'checkbox',
        isReadOnly: false,
        isHidden: false,
        isRequired: false
    },
    {
        id: 'DMT_Booking_System_Code__c',
        label: 'Booking System Code',
        apiName: 'DMT_Booking_System_Code__c',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: true,
        isHidden: false,
        isRequired: false
    },
    {
        id: 'DMT_Clan_File_Id__c',
        label: 'Id Expedient Clan',
        apiName: 'DMT_Clan_File_Id__c',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: true,
        isHidden: false,
        isRequired: false
    },
    {
        id: 'DMT_Clan_File_Status__c',
        label: 'Status Expedient Clan',
        apiName: 'DMT_Clan_File_Status__c',
        value: '',
        size: '1-of-2',
        type: 'text',
        isReadOnly: true,
        isHidden: false,
        isRequired: false
    },
    {
        id: 'DMT_Defense_Due_Diligence__c',
        label: 'Defense Due Diligence required',
        apiName: 'DMT_Defense_Due_Diligence__c',
        value: false,
        size: '1-of-2',
        type: 'checkbox',
        isReadOnly: false,
        isHidden: false,
        isRequired: false,
        linkUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSeL9Q8oTfItwkP9yGHImCGrNipBwSZmDEKmVv-WV3ielt_LnQ/viewform',
        linkLabel: 'Defense Due Diligence Form'
    },
    {
        id: 'DMT_Under_X_Selling_Monitoring__c',
        label: 'Under X Selling Monitoring',
        apiName: 'DMT_Under_X_Selling_Monitoring__c',
        value: false,
        size: '1-of-2',
        type: 'checkbox',
        isReadOnly: false,
        isHidden: false,
        isRequired: false
    },
    {
        id: 'DMT_NewClient__c',
        label: 'New Client',
        apiName: 'DMT_NewClient__c',
        value: false,
        size: '1-of-2',
        type: 'checkbox',
        isReadOnly: false,
        isHidden: false,
        isRequired: false
    },
    {
        id: 'DMT_Business_Approval_Date__c',
        label: 'Business Approval Date',
        apiName: 'DMT_Sanction__r.DMT_Bussiness_Approved_Date__c',
        sourceField: 'Opportunity.DMT_Sanction__r.DMT_Bussiness_Approved_Date__c',
        value: '',
        size: '1-of-2',
        type: 'date',
        isReadOnly: true,
        isHidden: true,
        isRequired: false,
        hideWhenEmpty: true
    },
    {
        id: 'DMT_Business_Approval_Term__c',
        label: 'Business Approval Term',
        apiName: 'DMT_Sanction__r.DMT_Business_Approval_Term_n__c',
        sourceField: 'Opportunity.DMT_Sanction__r.DMT_Business_Approval_Term_n__c',
        value: '',
        size: '1-of-2',
        type: 'numberWithSuffix',
        isReadOnly: true,
        isHidden: true,
        isRequired: false,
        hideWhenEmpty: true,
        extraText: 'Month(s)',
        showCounterButtons: false
    },
    {
        id: 'DMT_Risk_Approval_Date__c',
        label: 'Risk Approval Date',
        apiName: 'DMT_Sanction__r.DMT_ApprovalDate__c',
        sourceField: 'Opportunity.DMT_Sanction__r.DMT_ApprovalDate__c',
        value: '',
        size: '1-of-2',
        type: 'date',
        isReadOnly: true,
        isHidden: true,
        isRequired: false,
        hideWhenEmpty: true
    },
    {
        id: 'DMT_Risk_Approval_Term__c',
        label: 'Risk Approval Term',
        apiName: 'DMT_Sanction__r.DMT_Risk_Approval_Term__c',
        sourceField: 'Opportunity.DMT_Sanction__r.DMT_Risk_Approval_Term__c',
        value: '',
        size: '1-of-2',
        type: 'numberWithSuffix',
        isReadOnly: true,
        isHidden: true,
        isRequired: false,
        hideWhenEmpty: true,
        extraText: 'Month(s)',
        showCounterButtons: false
    }
];